### ISSUE TITLE
Opposed test rolled by player

### ISSUE THREAD

**Issue by Yasnen** [Jagusti/fvtt-wfrp4e-gmtoolkit#105]
![2022-05-26 (6)](https://user-images.githubusercontent.com/46295990/170450123-e0e97663-f6a5-4ecf-9d1f-7e08bc5098d5.png)
When a player rolls a opposed test, an error is displayed and the advantage is not automatically updated.

**Comment by Jagusti** [comment]
Jus breaking this down ... 

* The "lacks permission to update ChatMessage" error is a permissions issue, triggered as part of the Opposed Test functionality within the wfrp4e system.  GM Toolkit won't change that. 
* The "lacks permission to update Token" is because the Player doesn't have Owner permission over the token actor. 

Giving players Owner permission isn't desirable for creatures and NPCs (or making them Assistant GMs), but would be necessary to update the token data, given the current way it's handled.  It's a workaround, but not especially satisfactory.

Alternatively I'll to do need some investigation to see whether I can intercept the update and handle it as a GM user.  I'm not sure I have a good way to handle this at the moment.

**Comment by Yasnen** [comment]
I understood the situation, the WFRP4e system was designed to request the GM to activate the Effects if the user is to activate it, due to a similar situation when the WFRP4e system executes the Effects process. Just an idea, but is it difficult to implement something like this?

**Comment by Jagusti** [comment]
It's hard for me! I think I got it so that the player' Advantage gets updated, but that's still leaves the non-owned token without an update 

Options I'm considering are 
- a message to the GM with a button in chat to update it (a bit like how the Dark Whispers action buttons are sent to a user)
- Intercepting the whole transaction and running it as the logged in GM. 

The latter is harder, but could help solve a few things for me.

**Comment by gravagehulk** [comment]
As of the latest update to WFRP4e (5.4) and this module, we are still getting errors in our world. It happens whenever we add players to the combat tracker and it resets or modifies their advantage. All players get these errors for other players. I thought that last version of this module was supposed to fix that.

**Comment by Jagusti** [comment]
This sounds like it may be a different error to the original posted? Could you post details of what the error is you get are getting please. If it's not r same user permission related one, it would be fine (and preferable) to raise a new issue, as this is already closed, and I wouldn't want it to get lost. Thanks @gravagehulk .

**Comment by gravagehulk** [comment]
Apologies. I was certain the error we were getting was identical. We have our regular game tomorrow night. I will attempt to screenshot the console error and open a new issue. From what I can tell, it happens for ever player every time every other player gets their advantage updated by the auto advantage system. And the error references not having permission to update the other players' tokens.

**Comment by Jagusti** [comment]
Yea, sounds like a new can of worms opened when trying to put a kid on the old can of worms. When you get the details tomorrow, please do raise the issue and I'll take a look. Any info you have on your player roles and your Foundry settings will be handy too -  specifically whatever your Toolkit Advantage settings are and whether you are using group advantage (in system settings). Thanks
