### ISSUE TITLE
[Feature Request] Deal Damage to Targeted Tokens

### ISSUE THREAD

**Issue by Havoclivekiller** [Jagusti/fvtt-wfrp4e-gmtoolkit#158]
Sometimes you want to deal damage to tokens and not do the math. While a lot is automatic, right now, we don't have the revamp to Overcast rules from the Winds of Magic rulebook, thus I was doing any damage by hand. I did make a 'weapon' to deal damage from that but it takes +SL to increase damage (need to play around with that).

What I would like to see is a macro that takes tokens targeted by GM, pops a window, and allows to choose to Ignore TB/AP as well as how much damage to input. The macro should consider Ward and Robust, and any other effect that would decrease damage (not counting custom ones in Effects).

**Comment by Jagusti** [comment]
Thanks for the suggestion @Havoclivekiller . I'll come back to this once I've got v10 sorted. In the meantime, initial thoughts: 

* The basic implementation should be straightforward, and would use the [applyBasicDamage()](https://github.com/moo-man/WFRP4e-FoundryVTT/blob/fa506c219b170deae368c2eb7224393386d779af/modules/actor/actor-wfrp4e.js#L1970-L2008) actor method. 
* The method allows to choose whether to `set minimum 1 damage`, which seems like a good option to include. 
* Ignoring armour is trickier, as you need to know the armour location. By default, 'body' is assumed by the actor method, but I guess being able to specify hit location (appropriate to the token targeted) ought to be an option too. At which point, things start getting more complex. 
* Catering for different Talents adds more complexity. Be good to have a list of what needs to be factored in.
* Entering a preset amount of damage makes sense for an initial implementation. 
  * Is there a use case for this to be randomised? I'd expect the UX be to use the same field to enter dice syntax instead of a plain number.
  * Randomised per target, or once for all targets? 

Some things to mull over.

**Comment by Jagusti** [comment]
There's a macro sorted for this. But I've decided to convert it into a Toolkit application, much like Group Tests. That way I can leverage a more consistent UI and some underlying reusable features. 

- [x] Pre-selects targeted tokens or party/entourage members if none are targeted or present in scene (can be manually tweaked in UI)
- [x] Validates damage to ensure an integer or a valid roll formula is submitted
- [x] Option to randomise hit location and/or damage for each target
- [x] Select hit location, or none, or random (based on individual tokens hit location, of randomising for each token)
- [x] Options to ignore TP and/or AP
- [x]  Single chat message to summarise damage to individual targets
- [x] Summary message shows hit location and random damage if applicable
- [x] Summary message shows which targets are reduced to 0 Wounds
- [x] Summary chat message is a GM whisper to avoid spoilers about adversaries
- [x] Default settings are good for most of the Other Damage mechanics in Core Rulebook, such as exposure, thirst, falling short distances (1d10 damage, less TB, ignoring AP)
- [x] Localisation - a lot of new terms to add
- [x] Add a funky new macro icon in keeping with the rest of the Toolkit

Once those final bits are sorted, then it's good to ship. 

I might eventually get round to adding
- [ ] a silent run version for one click macro operation
- [ ] chat command 
- [ ] reason field to explain why characters are getting hurt
