### ISSUE TITLE
Double Advantage on Dual Wielding

### ISSUE THREAD

**Issue by FatGiwafe** [Jagusti/fvtt-wfrp4e-gmtoolkit#205]
## Checklist

- [ ] I can be reached on Discord by my handle: Bell Pepper#1829

### Versions
 - Foundry VTT:  
 - WFRP4e System: 
 - GM Toolkit:  
 - Macro (if applicable): 

## Description

I have a Slayer in my game who uses Dual Wielder. In the text it says that he would only gain advantage if both attacks hit. But on VTT, advantage is gained with each attack. 

### What should happen
The Slayer should get an advantage only IF he lands BOTH attacks

### What is happening
The Slayer is getting an advantage with EACH attack

## Steps to reproduce the issue

1. Select Target
2. Make an attack with his main hand weapon
3. Check "Dual Wielding" in the attack roll
4. Roll
5 Advantage is produced

### Foundry Support Report
Foundry Virtual Tabletop: Version 9, 9.280
Game System: wfrp4e, 5.4.1
Active Modules: 14
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 3090 Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 6296 x 4672 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 118 | Ambient Lights: 6 | Ambient Sounds: 0 | Tiles: 5 | Tokens: 2

Actors: 67 | Items: 18 | Journal: 312 | Rollable Tables: 52 |
Playlists: 11 | Compendium Packs: 31 | Chat Messages: 216

**Comment by Jagusti** [comment]
Hi @FatGiwafe ... Cheers for raising this. Could you update the post above with Toolkit version please, and confirm whether or not you are using group advantage? 

Note that if I do need to make a change, then it's going to be in the current version of Toolkit (v6), which is compatible with latest WFRP (v6) and FVTT (v10).

**Comment by FatGiwafe** [comment]
Hello ! Thanks for the quick answer !

Post updated , turns out I'm using the previous version. Is V10 stable enough to use ?
Also, I couldn't find group advantage.

**Comment by Jagusti** [comment]
Hey there ... Group Advantage is round the bottom of the System settings, rather than GM Toolkit module settings. If you haven't found it, it's probably safe to you aren't using it! :)  I can't see the version of Toolkit in the original post - if you're on WFRP v5.4.1, you should be on Toolkit 0.9.4.4. 

v10 is stable AFAIK ... and the version of Toolkit v6.0.1 that supports it has some improvements over 0.9.4.4.  You don't have many modules, but it's worth checking that they have v10 versions if you depend on them before upgrading (and backing up your world of course). But we digress ... :)

**Comment by FatGiwafe** [comment]
Group advantage is indeed unchecked !

I am indeed on WFRP v5.4.1 and Toolkit 0.9.4.4
