### ISSUE TITLE
v11 - Secret Group test not working

### ISSUE THREAD

**Issue by LeRatierBretonnien** [Jagusti/fvtt-wfrp4e-gmtoolkit#235]
When using the "Secret Group Test" macro from the v6.0.4 compendium, the following error is displayed : 
![image](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/assets/1085008/0abb78d8-5398-41b7-a1f5-26a93d0d890f)

In addition, the "Group test settings" in the Foundry settings area is empty : 
![image](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/assets/1085008/c0d08658-8976-4ce2-bf42-dcd32ea641a9)

**Comment by Jagusti** [comment]
Hi ... I can't reproduce this on v10.291 or v11.300 under WFRP4e 6.5.8 and GMT 6.0.4, using v0.9.5 (2022-08-04) of the macro. 

- [ ] Can you confirm the **versions** of Foundry, wfrp4e system, Toolkit and the macro please
- [ ] Can you tell me **steps to reproduce** the first error?
- [ ] At what point in that sequence the **console error** shows.

Some things to try which might help diagnose. If you can have a go and let me know what happens in each case, that would be great. 

- [ ] **Run Interactive Test**
The first error suggests you might be running the group test silently. Can you check and set line 23 of the macro to 
```js
const interactive = true
```

- [ ] **Run Silent Test with Specified Test Skill**
When that line sets `interactive = false`, can you also uncomment line 14 which will specify a `testSkill` parameter.

- [ ] **Disable Babele**
Are you using Babele? If so, what happens when you try to launch group test if it is disabled?  You will need to re-launch the world for the Toolkit skill list to rebuild (though I expect that will happen anyway if Babele is turned off). 

- [ ] **Run from Macro Directory**
Are you running the macro directly from the compendium, or have you imported it into the world and are running it directly from the GM Toolkit folder in the Macro Directory (and not a hotbar shortcut)? 

- [ ] Are the **other GM Toolkit settings** functioning as expected, especially Dark Whispers and Module Maintenance?

**Comment by LeRatierBretonnien** [comment]
Hi ! I did some checks and investigations, and found that the issue is linked to the French WFRP4 module.
It is related to some obscure effects in psychologies and mutations : it is fixed now !
I close the issue :)

**Comment by LeRatierBretonnien** [comment]
Closing
