### ISSUE TITLE
Compatibility 0.8.x

### ISSUE THREAD

**Issue by Havoclivekiller** [Jagusti/fvtt-wfrp4e-gmtoolkit#57]
Soon the WFRP4e main system/modules will be updated to 0.8.x and there is some code reworked there. This module might need an update too.

**Comment by bluetardis** [comment]
Let me know if you need help with testing.

**Comment by Jagusti** [comment]
Thanks both ... much appreciated. 
I have indeed been waiting for the system to be updated and stabilised for FVTT 0.8.x compatibility. There is a new branch for `v8comp` where I'm focussing on the updates needed. Many of the macros are straightforward, but there is some more challenge around the Token Hud.

**Comment by Jagusti** [comment]
Attached is a snapshot of the v8comp branch which AFAIK should resolve any compatibility issues with FVTT 0.8.x and WFRP 4.x.  It also pre-empts some, but not all v9 deprecation issues. If you want to take a look your feedback is welcome. Otherwise I'll aim to push a v8 release on Friday. 

[fvtt-wfrp4e-gmtoolkit-v8comp.zip](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/files/6933887/fvtt-wfrp4e-gmtoolkit-v8comp.zip)

There are some significant refactors needed for some macros - particularly Set Token Vision and Light - which will wait until the v9 canvas changes are stable. I'm also intending to separately make some changes to Send Dark Whispers and other macros to improve user/actor targeting. Those changes (such as #40 and #58) are out of scope for this.  I probably ought to get my backlog updated!

**Comment by Jagusti** [comment]
Includes further fixes up to https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/ec892f1b4c7436387ac8b774213974126fda7c37

- various fixes for Token Hud Extension
- further localisation for Send Dark Whispers macro 
- French translation improvements

[fvtt-wfrp4e-gmtoolkit-8comp.zip](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/files/6936438/fvtt-wfrp4e-gmtoolkit-8comp.zip)

**Comment by bluetardis** [comment]
Looks good so far.  Doing more testing tomorrow!
